#[cfg(feature = "discord")]
pub mod discord;
#[cfg(feature = "github")]
pub mod github;
#[cfg(feature = "google")]
pub mod google;

#[cfg(feature = "amazon-cognito")]
pub mod amazon_cognito;
#[cfg(feature = "anilist")]
pub mod anilist;
#[cfg(feature = "apple")]
pub mod apple;
#[cfg(feature = "atlassian")]
pub mod atlassian;
#[cfg(feature = "auth0")]
pub mod auth0;
#[cfg(feature = "authentik")]
pub mod authentik;
#[cfg(feature = "autodesk")]
pub mod autodesk;
#[cfg(feature = "battle-net")]
pub mod battle_net;
#[cfg(feature = "bitbucket")]
pub mod bitbucket;
#[cfg(feature = "box-oauth")]
pub mod box_oauth;
#[cfg(feature = "bungie")]
pub mod bungie;
#[cfg(feature = "coinbase")]
pub mod coinbase;
#[cfg(feature = "donation-alerts")]
pub mod donation_alerts;
#[cfg(feature = "dribbble")]
pub mod dribbble;
#[cfg(feature = "dropbox")]
pub mod dropbox;
#[cfg(feature = "epic-games")]
pub mod epic_games;
#[cfg(feature = "etsy")]
pub mod etsy;
#[cfg(feature = "facebook")]
pub mod facebook;
#[cfg(feature = "figma")]
pub mod figma;
#[cfg(feature = "forty-two")]
pub mod forty_two;
#[cfg(feature = "gitea")]
pub mod gitea;
#[cfg(feature = "gitlab")]
pub mod gitlab;
#[cfg(feature = "intuit")]
pub mod intuit;
#[cfg(feature = "kakao")]
pub mod kakao;
#[cfg(feature = "keycloak")]
pub mod keycloak;
#[cfg(feature = "kick")]
pub mod kick;
#[cfg(feature = "lichess")]
pub mod lichess;
#[cfg(feature = "line")]
pub mod line;
#[cfg(feature = "linear")]
pub mod linear;
#[cfg(feature = "linkedin")]
pub mod linkedin;
#[cfg(feature = "mastodon")]
pub mod mastodon;
#[cfg(feature = "mercado-libre")]
pub mod mercado_libre;
#[cfg(feature = "mercado-pago")]
pub mod mercado_pago;
#[cfg(feature = "microsoft-entra-id")]
pub mod microsoft_entra_id;
#[cfg(feature = "my-anime-list")]
pub mod my_anime_list;
#[cfg(feature = "naver")]
pub mod naver;
#[cfg(feature = "notion")]
pub mod notion;
#[cfg(feature = "okta")]
pub mod okta;
#[cfg(feature = "osu")]
pub mod osu;
#[cfg(feature = "patreon")]
pub mod patreon;
#[cfg(feature = "polar")]
pub mod polar;
#[cfg(feature = "reddit")]
pub mod reddit;
#[cfg(feature = "roblox")]
pub mod roblox;
#[cfg(feature = "salesforce")]
pub mod salesforce;
#[cfg(feature = "shikimori")]
pub mod shikimori;
#[cfg(feature = "slack")]
pub mod slack;
#[cfg(feature = "spotify")]
pub mod spotify;
#[cfg(feature = "start-gg")]
pub mod start_gg;
#[cfg(feature = "strava")]
pub mod strava;
#[cfg(feature = "synology")]
pub mod synology;
#[cfg(feature = "tiktok")]
pub mod tiktok;
#[cfg(feature = "tiltify")]
pub mod tiltify;
#[cfg(feature = "tumblr")]
pub mod tumblr;
#[cfg(feature = "twitch")]
pub mod twitch;
#[cfg(feature = "twitter")]
pub mod twitter;
#[cfg(feature = "vk")]
pub mod vk;
#[cfg(feature = "withings")]
pub mod withings;
#[cfg(feature = "workos")]
pub mod workos;
#[cfg(feature = "yahoo")]
pub mod yahoo;
#[cfg(feature = "yandex")]
pub mod yandex;
#[cfg(feature = "zoom")]
pub mod zoom;
